const {
  BookCharacterRepository,
  BookRepository,
  ChapterAudioExportRepository,
  ChapterAudioSkipRangeRepository,
  ChapterCharacterRepository,
  ChapterRepository,
  ChapterSegmentRepository,
  CharacterVoiceBindingRepository,
  DialogueRepository,
  JobRepository,
  ProviderVoiceRepository,
  StorageObjectRepository,
  VoiceFavoriteRepository,
  VoiceProfileRepository,
  SystemSettingRepository,
  ProviderUsageRepository,
  AiConfigRepository,
  TtsConfigRepository
} = require('./postgres/repositories');

module.exports = {
  bookRepository: new BookRepository(),
  chapterRepository: new ChapterRepository(),
  chapterSegmentRepository: new ChapterSegmentRepository(),
  chapterCharacterRepository: new ChapterCharacterRepository(),
  dialogueRepository: new DialogueRepository(),
  bookCharacterRepository: new BookCharacterRepository(),
  characterVoiceBindingRepository: new CharacterVoiceBindingRepository(),
  chapterAudioExportRepository: new ChapterAudioExportRepository(),
  chapterAudioSkipRangeRepository: new ChapterAudioSkipRangeRepository(),
  voiceProfileRepository: new VoiceProfileRepository(),
  providerVoiceRepository: new ProviderVoiceRepository(),
  voiceFavoriteRepository: new VoiceFavoriteRepository(),
  jobRepository: new JobRepository(),
  storageObjectRepository: new StorageObjectRepository(),
  systemSettingRepository: new SystemSettingRepository(),
  providerUsageRepository: new ProviderUsageRepository(),
  aiConfigRepository: new AiConfigRepository(),
  ttsConfigRepository: new TtsConfigRepository(),
};
